using System;
using Sirenix.OdinInspector;
using UnityEngine;
using UnityEngine.Serialization;

namespace Intrepid.Core.Themes
{
    [Serializable]
    public class Palettes
    {
        [FormerlySerializedAs("main")] // don't remove that...
        [Title("Bundle"), SerializeField, HideLabel, InlineProperty] private PaletteBundle bundle = new();
        
        [Title("Common Colors"), PropertySpace(10)]
        [SerializeField] private Color energyGauge = Color.yellow;
        [SerializeField] private Color o2Gauge = Color.cyan;
        [SerializeField] private Color counterFilling = Color.magenta;

        public PaletteBundle Bundle => bundle;
        public Color EnergyGaugeColor => energyGauge;
        public Color O2GaugeColor => o2Gauge;
        public Color CounterFillingColor => counterFilling;
    }
}